### PR TITLE
Dubai launches DEWAVerse Platform on Metaverse

### PR DESCRIPTION
**Pull request by Hassan-Mehmood**

### CODE REVIEW

**Comment by Hamzah-syed** [comment]
Hello Hasan, Kindly resolve the conflict and add this to the news section.

**Comment by Hassan-Mehmood** [comment]
> Hello Hasan, Kindly resolve the conflict and add this to the news section.

I think it has been solved, kindly check

**Comment by Hamzah-syed** [comment]
Put this news in the **Metaverse News section** like others. and remove the heading, you can add this after the Walmart news
image

**Comment by Hassan-Mehmood** [comment]
> Put this news in the **Metaverse News section** like others. and remove the heading, you can add this after the Walmart news image

Done

**Comment by Hamzah-syed** [comment]
Looks good thanks for your contribution.

**Pull request merged**
